darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/migration/models.py
from django.db import models
from django.contrib.auth.models import User
from darkoob.book.models import Book

class Hop(models.Model):
    migration = models.ForeignKey('Migration')
    host = models.ForeignKey(User, related_name='host_set')
    received_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (("migration", "host"),)

    def __unicode__(self):
        return unicode("%s - %s" % (self.migration, self.host.username))

class Migration(models.Model):
    book = models.ForeignKey(Book, related_name='book_set')
    starter = models.ForeignKey(User, related_name='starter_set')
    starter_message = models.TextField()
    start_time = models.DateTimeField(auto_now_add=True)
    private_key = models.CharField(max_length=10, unique=True)
 
    def get_user_hoped_migrations(self, user):
        '''return all migration's objects that hoped in user'''
        return [hop.migration for hop in Hop.objects.filter(host=user)]

    def get_user_host_migrations(self, user):
        '''return all migration's objects that hosted by user'''
        return [migrate for migrate in Migration.objects.filter(starter=user)]

    def get_user_related_migrations(self, user):
        '''return get_user_host_migrations() +  get_user_hoped_migrations()'''
        return self.get_user_hoped_migrations(user) + self.get_user_host_migrations(user)

    def __unicode__(self):
        return unicode("%s - %s" % (self.book.title, self.starter.username))

darkoob/social/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext
from django.contrib.auth import authenticate
from django.utils import timezone
from django.db.models import Q

from darkoob.social.models import UserProfile, UserNode
from darkoob.social.forms import RegisterForm, ChangePasswordForm, EditProfileForm, NewPostForm, CommentForm
from darkoob.post.models import Post, Comment
from darkoob.book.models import Quote
from darkoob.migration.models import Migration
from darkoob.group.models import Schedule
from django.utils import simplejson

from avatar.forms import PrimaryAvatarForm, DeleteAvatarForm
# from avatar.models import Avatar
from avatar.templatetags import avatar_tags


@login_required
def profile(request):
    form = EditProfileForm(request.POST)

    return render_to_response('social/profile.html',{'user': request.user, 'form': form})

def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            from datetime import date
            cd = form.cleaned_data      
            email = cd['email'] #TODO: Email should be unique 
            user = User.objects.create_user(username = email, password = cd['password'], email = cd['email'])
            user.first_name = cd['first_name']
            user.last_name = cd['last_name']
            UserProfile.objects.filter(user = user).update(birthday = date(cd['year'], cd['month'], cd['day']))
            if cd['sex'] == 'Female':
                UserProfile.objects.filter(user=user).update(sex = 'Female')
            else:
                UserProfile.objects.filter(user=user).update(sex = 'Male')
            user.save()
            # u = authenticate(email, cd['password'])
            # return HttpResponseRedirect(reverse('social:home'))
            return render_to_response('registered.html',{'firstname':cd['first_name']})
        else:
            return HttpResponseRedirect(reverse('index'))

    elif request.method == 'GET':
        #TODO: Initial return page's fields 
        form = RegisterForm( 
            # initial = {'username': 'initial'}
        )
        return render_to_response('signup.html', {'form':form})
    else:
        return HttpResponseRedirect(reverse('index'))

@login_required
def change_password(request):
    ##
    ## Please Dont remove:D
    ##
    # print ',,,,,,,,,,,', UserNode.index.search(user_id=27)[0]
    a = UserNode.index.get(user_id=request.user.id)
    # print a

    # print "User 1 follows {}".format(a.following.all())
    # print "User 1's followers {}".format(a.followers.all())
    # print a.is_follow(2)
    # print a.followers.all()
    # a.follow_person(2)
    # print a.follow_person(2)
    # print a.follow_person(3)

    # print '------------', a
    # b = UserNode.index.get(user_id=2)
    # c = UserNode.index.get(user_id=202)
    # print a, b , c
    # a.save()
    # b.save()

    # d = UserNode.index.search(user_id=53)
    # e = UserNode(user_id=114)
    # e = UserNode.index.get(user_id=114)
    # print "eeeeeeeeee",e
    # e.save()
    # e = UserNode.index.get(user_id=114)


    # a.follow_person(201)
    # b.follow_person
    # print a.get_followers(), a.get_following()
    # print b, c , d
    # a.follow_person(114)
    # print "-----------------------------------"
    # print b , c , d , e
    # print 

    # for i in  a.get_followed():
        # print i.user_id

    # a.follow.connect(b)
    # a.follow.connect(c)
    # a.follow.connect(d)
    # a[0].save()
    # print "-----------------------------------"
    # print UserNode.index.search(user_id=26)[0].get_follows()
    # from darkoob.migration.models import Migration, Hop

    # # print Migration.objects.all()[0].hop_set.filter()
    # # print "khkh", UserProfile.objects.get(user=request.user).get_related_migrations()
    # m = Migration() 
    # print m.get_user_related_migrations(request.user)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            comment = Comment(
                author=request.POST['author'],
                comment=request.POST['comment'],
            )
            if form.cleaned_data['parent_id'] != '':
                comment.parent = Comment.objects.get(id=request.POST['parent_id'])
            comment.save()
    else:
        form = CommentForm()
    # if this is a reply to a comment, not to a post
    # if form.cleaned_data['parent_id'] != '':
    #     comment.parent = Comment.objects.get(id=request.POST['parent_id'])
    # comment.save()

    # if request.method == 'POST':
    #     form = ChangePasswordForm(request.POST)
    #     if form.is_valid():
    #         cd = form.cleaned_data
    #         if request.user.check_password(cd['password']):
    #             user = User.objects.get(username = request.user.username)
    #             user.set_password(cd['new_password'])
    #             user.save()
    #             return HttpResponse('Succsessfull! Password has been changed')
    #             #TODO: Send Email to user
    #         else: 
    #             pass
    #             #TODO: Raise Error('Your Password is not correct')

    # else:
    #     form = ChangePasswordForm()
    return render_to_response('change_password.html', {'user': request.user, 'form': form})

@login_required
def home(request):
    template = 'social/home.html'
    posts = Post.objects.order_by("-submitted_time")
    count = range(1, len(posts) + 1)
    groups = request.user.group_set.all()
    admin_groups = request.user.admin_set.all()
    book_deadlines = []
    for group in admin_groups:
        for schedule in group.schedule_set.all():
            deadline_set = schedule.deadline_set.all()
            for i in range(len(deadline_set)):
                deadline_set[i].time_percentage = (timezone.now() - deadline_set[i].start_time).total_seconds()  / (deadline_set[i].end_time - deadline_set[i].start_time).total_seconds() * 100
            book_deadlines.append([ schedule.book , deadline_set])
    for group in groups:
        for schedule in group.schedule_set.all():
            deadline_set = schedule.deadline_set.all()
            for i in range(len(deadline_set)):
                deadline_set[i].time_percentage = (timezone.now() - deadline_set[i].start_time).total_seconds()  / (deadline_set[i].end_time - deadline_set[i].start_time).total_seconds() * 100

            book_deadlines.append([ schedule.book , deadline_set])
        
    if request.is_ajax():
        template = 'post/posts.html'

    m = Migration() 
    # print m.get_user_related_migrations(request.user)

    # Todo: Change this part
    suggestion_list = User.objects.order_by('?')[0:4]    # TODO : ISSUE #54


    #
    from darkoob.book.models import Book, Author
    try:
        quote = Quote.objects.order_by('?')[0]
    except:
        author= Author.objects.create(name='vahid')
        quote = Quote.objects.create(author=author, text="... to sath abstractioneton")

    # print "--------------------", posts[0].noks._get_votes()
    return render(request, template, {
        'new_post_form': NewPostForm(),
        'posts': posts,
        'count': count[::-1],
        'groups': groups,
        'admin_groups': admin_groups,
        'book_deadlines': book_deadlines,
        'quote': quote,
        'migrations': m.get_user_related_migrations(request.user),
        'suggestion_list': suggestion_list,
    })

@login_required
def user_following(request, username):
    try:
        user = User.objects.get(username=username)
    except:
        raise Http404
    else:
        template = 'social/user_following.html'
        user_node = UserNode.index.get(user_id=user.id)
        following = [User.objects.get(id=node.user_id) for node in user_node.following.all()]
        count = range(1, len(following) + 1)

        if request.is_ajax():
            template = 'social/person_bar_page.html'

        return render(request, template, {
            'person': following,
            'count': count[::-1],
        })

        return render(request, 'social/user_profile.html', {'username': username})

@login_required
def user_followers(request, username):
    try:
        user = User.objects.get(username=username)
    except:
        raise Http404
    else:
        template = 'social/user_followers.html'
        user_node = UserNode.index.get(user_id=user.id)
        followers = [User.objects.get(id=node.user_id) for node in user_node.followers.all()]
        count = range(1, len(followers) + 1)

        if request.is_ajax():
            template = 'social/person_bar_page.html'

        return render(request, template, {
            'person': followers,
            'count': count[::-1],
        })

        return render(request, 'social/user_profile.html', {'username': username})

@login_required
def following(request):
    '''A view for showing all following users of logged in user'''

    template = 'social/following.html'
    user_node = UserNode.index.get(user_id=request.user.id)
    following = [User.objects.get(id=node.user_id) for node in user_node.following.all()]
    count = range(1, len(following) + 1)

    if request.is_ajax():
        template = 'social/person_bar_page.html'

    return render(request, template, {
        'person': following,
        'count': count[::-1],
    })

@login_required
def followers(request):
    '''A view for showing all followers users of logged in user'''
    
    # start cleanup code 
    template = 'social/followers.html'
    user_node = UserNode.index.get(user_id=request.user.id)

darkoob/social/templates/social/favorite_books.html
{% extends "social/user_profile.html" %}
{% load staticfiles %}
{% block favorite_book_active %}
<li class="active">
  <a href="{% url 'social:user_favorite_books' username=user.username %}"><i class="icon-star"></i> Favorite Books</a>
</li>
{% endblock favorite_book_active %}

{% block right_sidebox %}
  <div class="sidebox post">
    <p>
      <b>{{ user.first_name|capfirst }}'s Favorite Books</b>
      {% include 'social/favorite_books_page.html' %}
    </p>

  </div>
{% endblock right_sidebox %}

darkoob/social/templates/social/followers.html
{% extends "base/profile_base.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}
{% block js %}
<script type="text/javascript" src="{% static "js/sticky.js" %}"></script>
<link rel="stylesheet" href="{% static "css/sticky.css" %}" type="text/css" />


  <script src="{% static "js/jquery.min.js" %}" type="text/javascript" charset="utf-8" ></script>
  <script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
  <script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
{% endblock js %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="sidebox post">
          <h4> Followers </h4>
          {% include 'social/person_bar_page.html' %}
        </div> <!-- post -->
      </div> <!-- span12 -->
    </div> <!-- row -->
  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock %}

darkoob/social/templates/social/followers_page.html
{% load endless %}
{% paginate 1,1 followers %}
{% for user in followers %}
<div class="row-fluid">
  <div class="span12">
    <div class="sidebox post">
      <div class="row-fluid">
        <div class="post_head">
          <div class="span2">
            <div class="thumb">
            </div>
          </div> <!-- span2 -->
          <div class="span9">
            <div class="username">
              {{ user }}
            </div>
          </div> <!-- span9 -->
          <div class="span1 pull-right">
            <div class="submitted_time">

            </div>
          </div> <!-- span1 -->
        </div> <!-- post_head -->
      </div> <!-- row -->
      <div class="row-fluid">
        <div class="span12">
          <div class="post_content">

          </div> <!-- content -->
        </div> <!-- span12 -->
      </div> <!-- sidebox post -->
    </div> <!-- span12 -->
  </div> <!-- row -->
{% endfor %}
{% show_more %}

darkoob/social/templates/social/following.html
{% extends "base/profile_base.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}
{% block js %}
<script type="text/javascript" src="{% static "js/sticky.js" %}"></script>
<link rel="stylesheet" href="{% static "css/sticky.css" %}" type="text/css" />


  <script src="{% static "js/jquery.min.js" %}" type="text/javascript" charset="utf-8" ></script>
  <script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
  <script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
{% endblock js %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="sidebox post">
          <h4> Following </h4>
          {% include 'social/person_bar_page.html' %}
        </div> <!-- post -->
      </div> <!-- span12 -->
    </div> <!-- row -->
  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock %}

darkoob/social/templates/social/following_page.html
{% load endless %}
{% paginate 1,1 following %}
    {% for user in following %}
        <div class="row-fluid">
          <div class="span12">
            <div class="sidebox post">
              <div class="row-fluid">
                <div class="post_head">
                  <div class="span2">
                    <div class="thumb">
                    </div>
                  </div> <!-- span2 -->
                  <div class="span9">
                    <div class="username">
                      {{ user }}
                    </div>
                  </div> <!-- span9 -->
                  <div class="span1 pull-right">
                    <div class="submitted_time">
                      
                    </div>
                  </div> <!-- span1 -->
                </div> <!-- post_head -->
              </div> <!-- row -->
              <div class="row-fluid">
                <div class="span12">
                  <div class="post_content">

                  </div> <!-- content -->
                </div> <!-- span12 -->
            </div> <!-- sidebox post -->
          </div> <!-- span12 -->
        </div> <!-- row -->
    {% endfor %}
{% show_more %}

darkoob/social/templates/social/login.html
{% extends "base/base.html" %}
{% load bootstrap_toolkit %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/index_style.less" %}">
{% endblock css %}
{% block title %}
Login
{% endblock title %}

{% block body %}
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span4 offset4 middle">
        <div class="row-fluid">
          <div class="span9 offset1 signup">
            <legend>Login</legend>

            {% if form.errors %}
              <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                Username or password are incorrect.
              </div>
            {% endif %}

            <form method="post" class="form-vertical" action="{% url "social:login" %}">
              {% csrf_token %}
              {% for field in form %}
                {{ field }}
              {% endfor %}
              <div class="form-actions">
                <button type="submit" class="btn btn-primary">Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- Container -->


{% endblock body %}

darkoob/social/templates/social/person_bar_page.html
{% load endless %}
{% load avatar_tags %}
{% paginate 1,1 person %}
{% for user in person %}
<div class="row-fluid">
  <div class="span12">
    <div class="sidebox post">
      <div class="row-fluid">
        <div class="media">
          <a class="pull-left" href="#">
            {% avatar user 70%}
          </a>
          <div class="media-body">
            <a href="{% url 'social:user_profile' username=user.username %}"><b>{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}</b></a>
            <br>
            <a class="btn btn-medium" href="#" style="float:right"><i class="icon-eye-open"></i></a>

            {{ user.userprofile.sex }}<br/>
            {% if user.userprofile.city %}{{ user.userprofile.city|capfirst }}/{{user.userprofile.city.country|capfirst}}{% endif %}
          </div>

        </div>

      </div> <!-- span12 -->
    </div> <!-- row -->
  </div>
</div>
{% endfor %}
{% show_more %}

darkoob/social/templates/social/signup.html
chera ino nemishnase?

darkoob/social/templates/social/todo-delete-this-file.html
{% load endless %}
{% paginate 1,1 favorite_books %}
    {% for book in favorite_books %}
        <div class="row-fluid">
          <div class="span12">
            <div class="sidebox post">
              <div class="row-fluid">
                <div class="post_head">
                  <div class="span2">
                    <div class="thumb">
                    </div>
                  </div> <!-- span2 -->
                  <div class="span9">
                    <div class="username">
                      {{ book }}
                    </div>
                  </div> <!-- span9 -->
                  <div class="span1 pull-right">
                    <div class="submitted_time">
                      
                    </div>
                  </div> <!-- span1 -->
                </div> <!-- post_head -->
              </div> <!-- row -->
              <div class="row-fluid">
                <div class="span12">
                  <div class="post_content">

                  </div> <!-- content -->
                </div> <!-- span12 -->
            </div> <!-- sidebox post -->
          </div> <!-- span12 -->
        </div> <!-- row -->
    {% endfor %}
{% show_more %}

darkoob/social/templates/social/user_followers.html
{% extends "social/user_profile.html" %}
{% load staticfiles %}

{% block followers_active %}
<li class="active">
  <a href="{% url 'social:user_followers' username=user.username %}" ><i class="icon-eye-open"></i> Followers 
  </a>
</li>
{% endblock followers_active%}

  {% block right_sidebox %}
  <div class="sidebox post">
    <p>
      <b>{{ user.first_name|capfirst }}'s Followers</b>
      {% include 'social/person_bar_page.html' %}
    </p>
  </div>
  {% endblock right_sidebox %}

darkoob/social/templates/social/user_following.html
{% extends "social/user_profile.html" %}
{% load staticfiles %}

{% block following_active %}
<li class="active">
    <a href="{% url 'social:user_following' username=user.username %}"><i class="icon-heart"></i> Following </a>
</li>
{% endblock following_active%}

{% block right_sidebox %}
<div class="sidebox post">
  <p>
    <b>{{ user.first_name|capfirst }}'s Following</b>
    {% include 'social/person_bar_page.html' %}
  </p>
</div>
{% endblock right_sidebox %}

darkoob/social/templates/social/user_profile.html
{% extends "base/profile_base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}
{% block title %}Darkoob - {{ user.get_full_name }} page{% endblock title %}

{% load avatar_tags %}

{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <div class="media">
      <a class="pull-left" href="#">
        {% avatar user 100 %}          
      </a>
      <div class="media-body">
        <h4 class="media-heading"><a href="{% url 'social:user_profile' username=user.username %}">{{user.first_name|capfirst}} {{user.last_name|capfirst}}</a></h4>
        {{ user.userprofile.sex }}<br />
        {{ user.userprofile.birthday }}<br />
        {% if user.userprofile.city %}{{ user.userprofile.city|capfirst }}/{{user.userprofile.city.country|capfirst}}{% endif %}
      </div>

    </div>
    <br/>
    {%if user.userprofile.mobile %}
    <b>Mobile</b> {{user.userprofile.mobile}}
    {% endif%}

    {% if user.userprofile.website %}
    <address>
      <b>Webpage</b> <a href="{{user.userprofile.website}}">{{user.userprofile.website|truncatechars:35}}</a>
    </address>
    {% endif%}


    {% if is_followers %}
      {{user.first_name|capfirst}} follow you <br>
    {% endif %}

    {% if is_following %}
      <button class="btn btn-small btn-block disabled" disabled="disabled" onclick="Dajaxice.darkoob.social.follow_person(follow_person_callback, {'user_id': {{user.id}}})"><i class="icon-eye-open"></i> You Follow {{user.first_name|capfirst}}
      </button>

    {% else %}
      <script type="text/javascript">
        function follow_person_callback(data){
          if(data.done){
            $.pnotify({
              title: 'Following',
              text: 'You follow {{user.get_full_name}} ',
              type: 'success',
              opacity: .8,
            });
            $('#follow_btn').attr('disabled', 'disabled');
            $('#follow_btn').attr('class', 'btn btn-small btn-block disabled');
          }
        }
      </script>
      <button id="follow_btn" class="btn btn-small btn-block" onclick="Dajaxice.darkoob.social.follow_person(follow_person_callback, {'user_id': {{user.id}}})"><i class="icon-eye-close"></i> Follow {{user.first_name|capfirst}}</button>
    {% endif %}
    
  
    <br/>

    <ul class="nav nav-tabs nav-stacked">
        {% block followers_active %}
        <li>
        <a href="{% url 'social:user_followers' username=user.username %}" ><i class="icon-eye-open"></i> Followers 
          <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock followers_active%}
        {% block following_active %}
        <li>
          <a href="{% url 'social:user_following' username=user.username %}"><i class="icon-heart"></i> Following <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock following_active%}
        {% block favorite_book_active %}
        <li>
          <a href="{% url 'social:user_favorite_books' username=user.username %}"><i class="icon-star"></i> Favorite Books <i class="icon-chevron-right" style="float:right"></i></a>
        </li>
        {% endblock favorite_book_active %}

      </ul>



      <div class="row-fluid">

        <div class="sidebox-head">
          <h4>{{user.first_name|capfirst }}'s Group</h4>
        </div>
        <div class="span12 simple_box">

        </div> <!-- span10 -->
      </div> <!-- row -->



    </div> <!-- span12 -->
  </div> <!-- row -->
  {% endblock sidebar %}

  {% block main %}


  <div class="row-fluid">
    <div class="span11 offset1">

      <div class="quote">
        <blockquote>
          <p>{{ user.userprofile.quote.text }}</p>
          {% if user.userprofile.quote.author %}<small>{{ user.userprofile.quote.author }}</small>{% endif %}
          {% if user.userprofile.quote.book %}<small>{{ user.userprofile.quote.book }}</small>{% endif %}
        </blockquote>
      </div>
      {% block right_sidebox %}

      <div class="sidebox-head" style="margin-left: 0;">
        <h4>Migrations</h4>
      </div>
      <div class="span12 simple_box" style="margin-left: 0;">


        <p>
          {% for migration in migrations %}
          <hops>
            <hop>
              <a style="Display:none">{{ migration.book.title }}</a>
              {% thumbnail migration.book.thumb "50x50" crop="center" as im %}
              <img rel="tooltip" title="d" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}
              <i class="icon-road"></i> 
            </hop>

            <hop>
              <a style="Display:none">{{ migration.starter.get_full_name }}</a>
              {% avatar migration.starter 30%}
            </hop>
            {% for hop in migration.hop_set.all|slice:":"|dictsort:"received_time" %}
            <i class="icon-chevron-right"></i>


            <hop>
              <a style="Display:none">{{ hop.host.get_full_name }}</a>
              {% avatar hop.host 30 %}
            </hop>
            {% endfor %}


          </hops>
          <br />
          {% endfor %}



          <script type="text/javascript">         

          $('hops hop').each(function(){

            $($(this).children()[1]).removeAttr('data-original-title')
            $($(this).children()[1]).attr('title',$(this).children()[0].text)
            $($(this).children()[1]).tooltip({
              'placement': 'bottom'
            });
          });

          </script>
        </p>

      </div>



      <div class="row-fluid">
        <div class="span12">
          {% include 'post/posts.html' %}
        </div>
      </div>

      <div class="row-fluid">
        <div class="span12">


        </div> <!-- span12 -->
      </div> <!-- row -->

      {% endblock right_sidebox %}




    </div> <!-- span12 -->
  </div> <!-- row -->
  {% endblock main %}