darkoob/book/urls.py
from django.conf.urls import patterns, include, url
from darkoob.book import views as book_views

urlpatterns = patterns('',
    url(r'^(?P<book_id>\d+)/(?P<book_title>\w+)/$', book_views.page, name='book_page'),
    url(r'^look/$', book_views.book_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),
)

darkoob/group/urls.py
from django.conf.urls import patterns, include, url
from darkoob.group import views as group_view
from darkoob.social import views as social_view

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/(?P<group_name>\w+)/$', group_view.group, name='group_page'),
    url(r'^new/$', group_view.create_group, name='create_group'),
    url(r'^look/$', social_view.user_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),

)

darkoob/search/urls.py
from django.conf.urls import patterns, include, url
from darkoob.search import views as search_views



urlpatterns = patterns('',
    url(r'^user/$', search_views.search_user),
    url(r'^users/$', search_views.search_user_result),
)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/search/models.py
from django.db import models

# Create your models here.

darkoob/group/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import AuthenticationForm

class GroupForm(forms.Form):
    name = forms.CharField(max_length=255)
    members = forms.CharField(widget=forms.HiddenInput())

darkoob/social/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.core.validators import validate_email
from django.contrib.auth.forms import AuthenticationForm

SEX_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)
MONTH_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
    (11, '11'),
    (12, '12'),
)
class CommentForm(forms.Form):
    author = forms.CharField()
    comment = forms.CharField()
    parent_id = forms.CharField(widget=forms.HiddenInput())


class AuthenticationFormPlaceholder(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={
            'id': 'id_username_auth',
            'placeholder': _('Username or Email'),
            'class': 'input-medium',
            'required': '',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'id_password_auth',
            'placeholder': _('Password'),
            'class': 'input-medium required',
            'required': '',
        })
    )

class EditProfileForm(forms.Form):
    month = forms.ChoiceField(choices = MONTH_CHOICES)

    day = forms.CharField(
        label = _('Day'),
        min_length = 1,
        max_length = 2,
        widget = forms.TextInput(attrs={
            'placeholder':_('Day'),
        })
    )

    year = forms.CharField(
        label = _('Year'),
        min_length = 4,
        max_length = 4,
        widget = forms.TextInput(attrs={
            'placeholder':_('Year'),
        })
    )

    # sex = forms.ChoiceField(
    #     choices = SEX_CHOICES,
    # )
    
    sex = forms.CharField(label=_('Sex'))
    mobile = forms.CharField(
        label = _('Mobile'),
        min_length = 7,
        max_length = 20,
        widget = forms.TextInput(attrs={
            'placeholder':_('Mobile'),
        })
    )

    website = forms.CharField(
        label = _('Website'),
        min_length = 4,
        max_length = 100,
        widget = forms.TextInput(attrs={
            'placeholder':_('Website'),
        })
    )

class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        label = _('Password'),
        min_length = 3,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Password'),
        })
    )

    new_password = forms.CharField(
        label = _('New password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('New password'),
        })
    )

    confirm_new_password = forms.CharField( # Why?!
        label = _('Re-type new password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Re-type new password'),
        })
    )

    def clean_confirm_new_password(self):
        confirm_new_password = self.cleaned_data['confirm_new_password']
        if confirm_new_password != self.cleaned_data['new_password']:
            raise forms.ValidationError(_('New password and Re-type does not match'))
        return confirm_new_password

class RegisterForm(forms.Form):
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    # username = forms.RegexField(label=_("Username"), max_length=30,
    #     regex=r'^[\w.@+-]+$',
    #     help_text=_("Required. 30 characters or fewer. Letters, digits and "
    #                   "@/./+/-/_ only."),
    #     error_messages={
    #         'invalid': _("This value may contain only letters, numbers and "
    #                      "@/./+/-/_ characters.")},
    #     widget=forms.TextInput(attrs={
    #         'placeholder': _('Username'),
    #         'class': 'span12 required',
    #         'required': '',
    #     }))

    first_name = forms.CharField(
        label = _('First Name'), 
        min_length = 2, 
        max_length = 30,
        widget = forms.TextInput(attrs={
            'placeholder':_('First Name'),
            'class': 'span6 required',
            'required': '',
        })
    )

    last_name = forms.CharField(
        label = _('Last Name'),
        min_length = 2,
        max_length = 30,
        widget = forms.TextInput(attrs={
            'placeholder':_('Last Name'),
            'class': 'span6 required',
            'required': '',
        })
    )
    email = forms.EmailField(
        label = _('E-Mail'),
        min_length = 5,
        widget = forms.TextInput(attrs={
            'placeholder': _('Your email address'),
            'type': 'email',
            'class': 'span12 required',
            'required': '',
        })
    )
    password = forms.CharField(
        label = _('Password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Password'),
            'class': 'span6 required',
            'required': '',
        })
    )
    confirm_password = forms.CharField(
        label = _('Re-type password'),
        min_length = 6,
        max_length = 30,
        widget = forms.PasswordInput(attrs={
            'placeholder':_('Re-type password'),
            'class': 'span6',
            'required': '',
        })
    )

    sex = forms.ChoiceField(choices=SEX_CHOICES)

    month = forms.ChoiceField(choices=MONTH_CHOICES,
        widget=forms.Select(attrs={
            'class': 'span4',
        })
    )

    day = forms.CharField(
        label = _('Day'),
        min_length = 1,
        max_length = 2,
        widget = forms.TextInput(attrs={
            'placeholder':_('Day'),
            'class': 'span4',
            'required': '',
        })
    )

    year = forms.CharField(
        label = _('Year'),
        min_length = 4,
        max_length = 4,
        widget = forms.TextInput(attrs={
            'placeholder':_('Year'),
            'class': 'span4',
            'required': '',
        })
    )

    def clean_day(self):
        day = int(self.cleaned_data['day'])
        if (day > 31 or day < 1):
            raise forms.ValidationError(_('Invalid date'))
        return day

    def clean_month(self):
        month = int(self.cleaned_data['month'])
        if (month > 12 or month < 1):
            raise forms.ValidationError(_('Invalid date'))
        return month

    def clean_year(self):
        year = int(self.cleaned_data['year'])
        if (year > 2012 or year < 1900):
            raise forms.ValidationError(_('Invalid date'))
        return year

    def clean_email(self):
        email = self.cleaned_data['email']
        from django.contrib.auth.models import User
        try:
            user = User.objects.get(email=email) 
        except User.DoesNotExist:
            return email
        else:
            # E-mail is a uniqe field 
            raise forms.ValidationError(_('You are member! Did you forget your password?'))

    def clean_password(self):
        password = self.cleaned_data['password']
        # Check strog password
        return password

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        if confirm_password != self.cleaned_data['password']:
            raise forms.ValidationError(_('Password and Re-type does not match'))
        return confirm_password

class NewPostForm(forms.Form):
    text = forms.CharField(
        label=_('Text'),
        widget=forms.Textarea(attrs={
            'placeholder': _('Say it!'),
            'rows': 3,
            'class': 'span12',
            'style': 'resize: none;',
        })
    )

darkoob/book/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.http import Http404
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext

from darkoob.book.models import Book
from django.utils import simplejson


from darkoob.book.models import Review

def page(request, book_id, book_title):
    book = Book.objects.get(id = book_id, title = book_title)
    template = 'book/book_page.html'
    reviews = Review.objects.filter(book=book).order_by("-submitted_time")
    count = range(1, len(reviews) + 1)

    if request.is_ajax():
        template = 'book/reviews.html'

    if book:
        return render(request, template ,{
            'book': book,
            'rate': book.rating.get_rating(),
            'reviews': reviews,
            'count': count[::-1],
        })
    else:
        raise Http404


from avatar.templatetags import avatar_tags


def book_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Book.objects.filter(title__icontains=value)
            results = [ {'book_title': x.title , 'photo': x.thumb.url , 'author_name': x.author_names() }  for x in model_results]

    to_json = []

    jt=simplejson.dumps(results)
    return HttpResponse(jt, mimetype='application/json')

darkoob/comments/views.py
# Create your views here.

darkoob/group/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from darkoob.group.forms import GroupForm
from darkoob.group.models import Group

def group(request, group_id, group_name):
    group = Group.objects.get(id=group_id, name=group_name)
    if group:
        group.admins = group.admin.admin_set.all()
        #group.members = group.members.all()
        return render(request, "group/group_page.html" ,{'group': group})
    else:
        return HttpResponse("Group Is not exist!")

@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            group = Group(name=cd['name'], admin=request.user)
            group.save()
            for member in cd['members'].strip(',').split(','):
                user = User.objects.get(username=member)
                group.members.add(user)
            group.save()
            
    else:
        form = GroupForm()
    return render(request, 'group/create_group.html', {'form': form })

darkoob/migration/views.py
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from darkoob.migration.forms import StartNewMigrationForm
from darkoob.book.models import Book
from darkoob.migration.models import Migration

import random
import string 
def generate_private_key(len=10):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(len))

def start_new_migration(request):
    if request.method == 'POST':
        form = StartNewMigrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                book = Book.objects.get(title=cd['book'])
            except:
                return HttpResponse("this book no exist")
            else:
                private_key = generate_private_key()
                Migration.objects.create(book=book, starter=request.user,
                    starter_message=cd['starter_message'], private_key=private_key
                )


                # TODO:Redirect to this page 
                return render(request, 'migration/started.html', 
                    {'private_key': private_key, 'book': book}
                )
    else:
        form = StartNewMigrationForm()
    return render(request, 'migration/start_new_migration.html', {'form': form, })

darkoob/post/views.py
# Create your views here.

darkoob/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.views.decorators.clickjacking import xframe_options_exempt
from darkoob.social.forms import AuthenticationFormPlaceholder, RegisterForm


def index(request, **kwargs):
    error = ''
    # if kwargs['errno']:
        # error = "An error has occured"
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('social:home'))
    return render(request, 'index.html', {
        'signup_form': RegisterForm(),
        'login_form': AuthenticationFormPlaceholder(),
        'error': error,
    })


@xframe_options_exempt
def ok_to_load_in_a_frame(request):
    return HttpResponse("This page is safe to load in a frame on any site.")

darkoob/templates/_comments.html
{% load comments %}
{% load mptt_tags %}

{% get_comment_list for object as comments %}

{% if comments %}
{% recursetree comments %}

<div {% if request.REQUEST.c|add:"0" == node.id %}id="newly_posted_comment"{% endif %}>
...comment content...
</div>
            <a name="c{{ node.id }}"></a>
            {{ node.comment }}
            {{ node.user }}
            {{ node.submit_date|timesince }} ago
            <a href="{{ object.get_absolute_url }}#c{{ node.id }}">#</a>
        {% render_comment_form for object %}

    {# recursion! children of a given comment #}
    {% if not node.is_leaf_node %}
        {{ children }}
    {% endif %}
{% endrecursetree %}
{% endif %}

{% render_comment_form for object %}

darkoob/templates/change_password.html
<html>
{% load avatar_tags %}

<a href='{% url "avatar_change" %}'>Change your avatar</a>
    {% load avatar_tags %}
    {% avatar user 1 %}
</html>

darkoob/templates/index.html
{% extends "base/base.html" %}

{% load staticfiles %}
{% load dajaxice_templatetags %}
{% load bootstrap_toolkit %}

{% block css %}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/index_style.less" %}">
{% endblock css %}

{% block js %}
<script type="text/javascript" src="{% static "/static/js/index.js" %}"></script>
{% endblock js %}

{% block title %}
Darkoob
{% endblock title %}

{% block body %}
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span6 offset3 top">
        <div class="row-fluid">
          <div class="span1 logo_img">
            <img src="{% static "/static/img/logo.png" %}">
          </div>
          <div class="span1 logo_text">
            Darkoob
          </div>
          <div class="span8 offset2">
            <form id="id_login_form" class="form-inline login" method="post" action="{% url "social:login" %}">
              {% csrf_token %}
              {% for field in login_form %}
                  {{ field }}
              {% endfor %}
              <input type="submit" value="Submit" class="btn btn-primary">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span6 offset3 middle">
        <div class="row-fluid">
          <div class="span9 offset1 signup">
            <legend>Sign up</legend>
          </div>
          <div class="span6 offset1 signup">
            <div id="id_form_error" class="alert alert-error" style="display: {% if error %}block{% else %}none{% endif %};">
              {{ error }}
            </div>
            <form id="id_signup_form" method="post" action="{% url "social:signup" %}">
              {% csrf_token %}
              <div class="controls">
                {# {{ signup_form.username }} #}
                {% if form.errors %}
                  <p style="color: red;">
                    Please correct the error{{ form.errors }} below.
                  </p>
                {% endif %}
              </div>
              <div class="controls controls-row">
                {{ signup_form.first_name }}
                {{ signup_form.last_name }}
              </div>
              <div class="controls controls-row">
                {{ signup_form.password }}
                {{ signup_form.confirm_password }}
              </div>
              <div class="controls">
                {{ signup_form.email }}
              </div>
              <div class="controls">
                {{ signup_form.sex }}
              </div>
              <div class="controls controls-row">
                {{ signup_form.year }}
                {{ signup_form.month }}
                {{ signup_form.day }}
              </div>
              <div class="form-actions">
                <button type="submit" class="btn btn-primary">Sign Up!</button>
                <button class="btn" onClick="reset_form();">Reset</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
  <script>
$("#id_signup_form").submit(function() {
  pass = $("#id_password");
  confirm_pass = $("#id_confirm_password");
  if (pass.val() == confirm_pass.val()) {
    return true;
  } else {
    console.log(pass.val() + " == " + confirm_pass.val());
    $("#id_form_error").css("display", "block").text("Your passwords don't match.");
    return false;
  }
})
</script>


{% endblock body %}
<script>
  $('form').bind('invalid', function(event) {
    event.preventDefault();
  });
</script>

darkoob/templates/registered.html
thank for registration {{firstname}} go to login page :D

darkoob/templates/search_base.html
{% load staticfiles %}
<html>
  <head>
    <title>AJAX SEARCH</title>
      <style>

        body {
          background-color: #FFF;
          font-size: 1.0em;
          font-family: “Lucida Grande”, Tahoma, Helvetica, sans-serif;
          color: #564b47;
          padding: 20px;
          margin: 0px;
          text-align: center;
            }

        div { 
          padding: 0;
          margin: 0; 
        }

        table { 
          width: 100%; 
          border: 1px solid #DDDDB2;
          border-spacing: 0;
          border-collapse: collapse; 
        }

        tr { 
          padding-bottom: 5px;
          border-bottom: 1px solid #CCC; 
        }

        tr.odd { background: #FFF; }

        tr.even { background: #FFFFD4; }

        td { 
          margin: 0; 
          padding: 5px 5px 5px 3px;
          vertical-align: top; 
        }

        td.right { text-align: right; }

        #centered {
          text-align: left;
          vertical-align: middle;
          margin: 0px auto;
          padding: 20px;
          width: 550px;
          background-color: #FFF;
          border: 1px solid #CCC;
          }
          // az inja kopyeye
        #spinner { 
          display: none;
          position: relative; 
        }

        div.padded { padding-top: 10px; }

        div.margin { margin-top: 20px; }

        div.clear { clear: both; }

        div.note {
          padding: 15px; 
          background: #FFFFD4;
          border: 1px solid #DDDDB2; 
        }

        .hint { 
          font-size: 0.8em;
          color: #888; 
        }

        input{
        	font-size:30px;
        	color:#444;
        	border:1px solid #ccc;
        	padding:5px 10px;
        	box-shadow:0px 1px 0px #fff;
          -moz-box-shadow:0px 1px 0px #fff;
          -webkit-box-shadow:0px 1px 0px #fff;
          -moz-border-radius:6px;
          -webkit-border-radius:6px;
          border-radius:6px;
          -khtml-border-radius:6px;
          margin:5px 10px;
        	width:540px;
        	height:50px;
        }

        input[type="submit"]{
        	font-size:20px;
        	height:40px;
        	font-weight: bolder;
        }

    </style>

    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
	  <script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
    <script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
    {% block extra_js %}{% endblock %}
  </head>
  <body>
    <div id="centered">
      {% block main %}{% endblock %}
    </div>
  </body>
</html>

darkoob/templates/search_user.html
{% extends 'search_base.html' %}
{% load staticfiles %}

{% block extra_js %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#searchSubmit').click(function() {
            q = $('#q').val();
            $('#results').html('&nbsp;').load('/users/?q=' + q);
        });
    });
    $(document).ajaxStart(function() {
        $('#spinner').slideDown('normal');//show();
    }).ajaxStop(function() {
        $('#spinner').slideUp('normal');//.hide();
    });
</script>
{% endblock %}

{% block main %}
<div>
    <div style="text-align:center">
        <strong>Looking For Members</strong>
    </div>
    <hr/>
    
    <input id="q" type="text" placeholder="Searching for..."/>
    <input id="searchSubmit" type="submit" value="Search" />
    
    <br/>
    <span class="hint">Type person name,family or username to search for users</span>
    <div class="margin">
        <span id="spinner"><img src="{% static "img/spinner.gif" %}"/></span>
        <div id="results"> </div>
    </div>
</div>
{% endblock %}

darkoob/templates/search_user_result.html
{% load endless %}
{% load staticfiles %}
{% if results|length %}
    <table>   
       <!-- <tr class='even'>
                <td colspan="3" class="right">
                    <strong>Found {{ results|length }} users</strong>
                </td>
            </tr>
        -->
        {% paginate 3,1 results %}
        {% for user in results %}
            <tr class={% cycle 'odd' 'even' %}>
                <td style="width:80px;">
                    <img src="{%static "img/an.jpg" %}" alt="Smiley face" style="width:80px;height:80px"  />
                </td>
                <td>
                    {{ user.first_name }} {{ user.last_name }}<br/>
                    <!-- 
                    <span class="hint">Gender:{% if user.userprofile.sex %}dd{%else%}ff{%endif%}</span>
                    <br/>-->
                </td>
                <td class="right">
                    <span class="hint">
                        Joined {{ user.date_joined|timesince }} ago 
                        <br/>
                        <a href="#">Follow</a>
                    </span>
                </td>
            </tr>
        {% endfor %}

    </table>
    {% show_more 'Other Results...'%}

{% else %}

    <div class="note">
        Your search yielded no results:D
    </div>
{% endif %}

darkoob/templates/signup.html
<html>
{% load bootstrap_toolkit %}
	{% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
	{% endif %}
    <form action="" method="post">
    	   {% csrf_token %}
        <table>
            {{ form|as_bootstrap }}
        </table>
        <div class="form-actions">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>


</html>