darkoob/book/urls.py
from django.conf.urls import patterns, include, url
from darkoob.book import views as book_views

urlpatterns = patterns('',
    url(r'^(?P<book_id>\d+)/(?P<book_title>\w+)/$', book_views.page, name='book_page'),
    url(r'^look/$', book_views.book_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),
)

darkoob/group/urls.py
from django.conf.urls import patterns, include, url
from darkoob.group import views as group_view
from darkoob.social import views as social_view

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/(?P<group_name>\w+)/$', group_view.group, name='group_page'),
    url(r'^new/$', group_view.create_group, name='create_group'),
    url(r'^look/$', social_view.user_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),

)

darkoob/search/urls.py
from django.conf.urls import patterns, include, url
from darkoob.search import views as search_views



urlpatterns = patterns('',
    url(r'^user/$', search_views.search_user),
    url(r'^users/$', search_views.search_user_result),
)

darkoob/social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from darkoob.social import views as social_views
from darkoob.social.forms import AuthenticationFormPlaceholder

urlpatterns = patterns('',
    url(r'^home/$', social_views.home, name='home'),
    url(r'^signup/$', social_views.signup, name='signup'),
    url(r'^login/$', auth_views.login,
        {'template_name': 'social/login.html',
         'authentication_form': AuthenticationFormPlaceholder
        }, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^change_password/$', social_views.change_password, name='change_password'),
    url(r'^profile/$', social_views.profile, name='profile'),

    url(r'^password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect': 'password/reset/done/'}, name='reset_pass'),
    url(r'^password/reset/done/$', auth_views.password_reset_done),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect': 'password/done/'}),
    url(r'^password/done/$', auth_views.password_reset_complete),

    url(r'^post/new/$', social_views.new_post, name='new_post'),
    url(r'^user/(?P<username>\w+)/$', social_views.user_profile, name='user_profile'),

    url(r'^user/(?P<username>\w+)/following$', social_views.user_following, name='user_following'),
    url(r'^user/(?P<username>\w+)/followers$', social_views.user_followers, name='user_followers'),
    url(r'^user/(?P<username>\w+)/favorite_books$', social_views.user_favorite_books, name='user_favorite_books'),

    url(r'^profile/followers/$', social_views.followers, name='followers'),
    url(r'^profile/following/$', social_views.following, name='following'),
    url(r'^profile/favorite_books$', social_views.favorite_books, name='favorite_books'),
)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/book/models.py
from django.db import models
from darkoob.social.models import User
from taggit.managers import TaggableManager
from djangoratings.fields import RatingField
from django.utils import timezone  
from sorl.thumbnail import ImageField

class Book(models.Model):
    title = models.CharField(max_length=255)
    publisher = models.ForeignKey('Publisher')
    language = models.ForeignKey('Language')
    authors = models.ManyToManyField('Author')
    tags = TaggableManager()
    thumb =  models.ImageField(upload_to='books/')
    rating = RatingField(range=5, can_change_vote=True, allow_delete=False, allow_anonymous=False)
    
    def author_names(self):
        return ', '.join([a.name for a in self.authors.all()])
    author_names.short_description = "Author Names"

    def __unicode__(self):
        return unicode(self.title)

class Publisher(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Language(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Author(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)

class Translator(models.Model):
    author = models.OneToOneField(Author)

    def __unicode__(self):
        return unicode(self.author)

class Translation(models.Model):
    book = models.ForeignKey(Book)
    translator = models.ForeignKey(Translator)
    language = models.ForeignKey(Language)

    def __unicode__(self):
        return unicode(self.book)

class Review(models.Model):
    book = models.ForeignKey(Book)
    user = models.ForeignKey(User)
    title = models.TextField()
    text = models.TextField()
    submitted_time = models.DateTimeField(default=timezone.now())
    rating = RatingField(range=5, can_change_vote=True, allow_delete=False, allow_anonymous=False)


    def __unicode__(self):
        return unicode(self.book) + unicode(self.user)

class Quote(models.Model):
    author = models.ForeignKey(Author)
    book = models.ForeignKey(Book, null=True, blank=True)
    text = models.TextField()

    def __unicode__(self):
        return unicode(self.text)

darkoob/comments/models.py
from django.db import models

# Create your models here.
from django.contrib.comments.models import Comment
from mptt.models import MPTTModel, TreeForeignKey

class MPTTComment(MPTTModel, Comment):
    """ Threaded comments - Add support for the parent comment store and MPTT traversal"""
    # a link to comment that is being replied, if one exists
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class MPTTMeta:
        # comments on one level will be ordered by date of creation
        order_insertion_by=['submit_date']

    class Meta:
        ordering=['tree_id','lft']

darkoob/search/models.py
from django.db import models

# Create your models here.

darkoob/comments/forms.py
from django import forms
from django.contrib.admin import widgets        
from django.contrib.comments.forms import CommentForm                            
from models import MPTTComment

class MPTTCommentForm(CommentForm):
    parent = forms.ModelChoiceField(queryset=MPTTComment.objects.all(), required=False, widget=forms.HiddenInput)

    def get_comment_model(self):
        # Use our custom comment model instead of the built-in one.
        return MPTTComment

    def get_comment_create_data(self):
        # Use the data of the superclass, and add in the parent field field
        data = super(MPTTCommentForm, self).get_comment_create_data()
        data['parent'] = self.cleaned_data['parent']
        return data

darkoob/group/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import AuthenticationForm

class GroupForm(forms.Form):
    name = forms.CharField(max_length=255)
    members = forms.CharField(widget=forms.HiddenInput())

darkoob/migration/forms.py
from django import forms
from django.utils.translation import ugettext as _

class StartNewMigrationForm(forms.Form):

    book = forms.CharField(
        label=_('Book'),
        widget=forms.TextInput(attrs={
            'placeholder': _('Book Name'),
            'autocomplete': 'off',
            'data-provide': 'typeahead',
            'class': 'span6 typeahead',
            'id': 'title-look',
            'sdf': 'dfsdf',            
        })
    )

    starter_message = forms.CharField(
        label=_('Your Message '),
        widget=forms.Textarea(attrs={
            'placeholder': _('Your Message'),
            'rows': 7,
            'class': 'span8',
        })
    )

darkoob/book/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.core.urlresolvers import reverse
from django.http import Http404
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext

from darkoob.book.models import Book
from django.utils import simplejson


from darkoob.book.models import Review

def page(request, book_id, book_title):
    book = Book.objects.get(id = book_id, title = book_title)
    template = 'book/book_page.html'
    reviews = Review.objects.filter(book=book).order_by("-submitted_time")
    count = range(1, len(reviews) + 1)

    if request.is_ajax():
        template = 'book/reviews.html'

    if book:
        return render(request, template ,{
            'book': book,
            'rate': book.rating.get_rating(),
            'reviews': reviews,
            'count': count[::-1],
        })
    else:
        raise Http404


from avatar.templatetags import avatar_tags


def book_lookup(request):
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'query'):
            value = request.GET[u'query']
            model_results = Book.objects.filter(title__icontains=value)
            results = [ {'book_title': x.title , 'photo': x.thumb.url , 'author_name': x.author_names() }  for x in model_results]

    to_json = []

    jt=simplejson.dumps(results)
    return HttpResponse(jt, mimetype='application/json')

darkoob/comments/views.py
# Create your views here.

darkoob/group/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from darkoob.group.forms import GroupForm
from darkoob.group.models import Group

def group(request, group_id, group_name):
    group = Group.objects.get(id=group_id, name=group_name)
    if group:
        group.admins = group.admin.admin_set.all()
        #group.members = group.members.all()
        return render(request, "group/group_page.html" ,{'group': group})
    else:
        return HttpResponse("Group Is not exist!")

@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            group = Group(name=cd['name'], admin=request.user)
            group.save()
            for member in cd['members'].strip(',').split(','):
                user = User.objects.get(username=member)
                group.members.add(user)
            group.save()
            
    else:
        form = GroupForm()
    return render(request, 'group/create_group.html', {'form': form })

darkoob/migration/views.py
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from darkoob.migration.forms import StartNewMigrationForm
from darkoob.book.models import Book
from darkoob.migration.models import Migration

import random
import string 
def generate_private_key(len=10):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(len))

def start_new_migration(request):
    if request.method == 'POST':
        form = StartNewMigrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                book = Book.objects.get(title=cd['book'])
            except:
                return HttpResponse("this book no exist")
            else:
                private_key = generate_private_key()
                Migration.objects.create(book=book, starter=request.user,
                    starter_message=cd['starter_message'], private_key=private_key
                )


                # TODO:Redirect to this page 
                return render(request, 'migration/started.html', 
                    {'private_key': private_key, 'book': book}
                )
    else:
        form = StartNewMigrationForm()
    return render(request, 'migration/start_new_migration.html', {'form': form, })

darkoob/post/views.py
# Create your views here.

darkoob/search/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.db.models import Q
from django.contrib.auth.models import User

import re



def search_user( request ):
    return render_to_response('search_user.html', {}, context_instance = RequestContext(request))

def search_user_result( request ):
    query_string = ''
    found_entries = None
    if request.is_ajax():
        q = request.GET.get('q')
        if q is not None:            
            query_string = request.GET['q']
            print 'query_string:',query_string
            entry_query = get_query(query_string,['first_name','last_name','username'] )
            print 'entry_query:',entry_query
            results = User.objects.filter(entry_query)
            print "results", results
            return render_to_response(
                'search_user_result.html',
                {'results':results,}, 
                context_instance = RequestContext(request),
            )
    return render_to_response('search_user_result.html', {})


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    """
    Splits the query string in invidual keywords, getting rid of unecessary spaces
    and grouping quoted words together.
    Example:
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    """
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
    aims to search keywords within a model by testing the given search fields.
    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

darkoob/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.views.decorators.clickjacking import xframe_options_exempt
from darkoob.social.forms import AuthenticationFormPlaceholder, RegisterForm


def index(request, **kwargs):
    error = ''
    # if kwargs['errno']:
        # error = "An error has occured"
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('social:home'))
    return render(request, 'index.html', {
        'signup_form': RegisterForm(),
        'login_form': AuthenticationFormPlaceholder(),
        'error': error,
    })


@xframe_options_exempt
def ok_to_load_in_a_frame(request):
    return HttpResponse("This page is safe to load in a frame on any site.")

darkoob/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load dajaxice_templatetags %}
<html>
<head>
  <title>{% block title %}Darkoob{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="content-type" content="text/html" charset=UTF-8">

  <link rel="stylesheet" type="text/less" href="{% static "/static/css/common_style.less" %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static "/static/bootstrap/css/bootstrap.min.css" %}">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static "/static/bootstrap/css/bootstrap-responsive.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/static/css/jquery.pnotify.default.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "/static/css/jquery.pnotify.default.icons.css" %}">
  {% block css %}
  {% endblock %}

  <script type="text/javascript" src="{% static "/static/js/jquery-1.9.1.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/jquery.validate.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/bootstrap/js/bootstrap.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/dajax/jquery.dajax.core.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/less-1.3.3.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/jquery.pnotify.min.js" %}"></script>
  <script type="text/javascript" src="{% static "/static/js/base.js" %}"></script>

  {% dajaxice_js_import %}

  {% block js %}
  {% endblock %}


</head>
<body>
  {% block body %}
  {% endblock body %}
  <!--  <em>{% block footer %}کلیه حقوق این سایت متعلق به استاد حسن نادری می باشد! {% endblock %}</em> -->

{% block bottom_js %}
{% endblock bottom_js %}
</body>
</html>

darkoob/templates/base/profile_base.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load dajaxice_templatetags %}
{% load avatar_tags %}

{% block css %}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/posts_style.less" %}">
{% endblock css %}

{% block js %}
<script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
<script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
<script type="text/javascript" charset="utf-8" src="{% static "/static/js/holder.js" %}"></script>
<script type="text/javascript" charset="utf-8">
    var endless_on_scroll_margin = 1;
</script>
<script type="text/javascript" src="{% static '/static/js/post.js' %}"></script>
{% endblock js %}

{% block title %}Homepage{% endblock title %}

{% block body %}
<script>
  function show_search_res(data) {
    if (!$("#search_results").length) {
      var lis = '<ul id="search_results" class="dropdown-menu" role="menu" aria-labelledby="sLabel">';
      for (i = 0; i < data['users'].length; i += 1) {
        lis = lis + '<li><a href="#">' + data['users'][i][0] + " &lt;" + data['users'][i][1] + "&gt;" + "</a></li>";
      }
      lis += '</ul>'
      $('#search').after(lis);
    }
  }
</script>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8 offset2">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand pull-left logo" href="{% url "social:home" %}">Darkoob</a>
            <form class="nav-search search_form pull-left" onSubmit="Dajaxice.darkoob.args_example(
              show_search_res, {'text':$('#search').val()})">
              <ul class="nav">
                <li>
                <input id="search" type="text" class="search-query input-xlarge dropdown-toggle"
                data-toggle="dropdown" autocomplete="off"
              onBlur="Dajaxice.darkoob.args_example(
              show_search_res, {'text':$('#search').val()})"
              placeholder="Search">
              <!--<ul id="search_results" class="dropdown-menu" role="menu" aria-labelledby="sLabel">
              </ul>-->
            </form>
            </li>
          </ul>
            <ul class="nav pull-right ">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                  {{ user.get_full_name }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a href="{% url "social:profile" %}"><i class="icon-user"></i> Profile</a></li>
                  <li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                  <li><a href="{% url "social:logout" %}"><i class="icon-off"></i> Logout</a></li>
                </ul>
              </li> <!-- dropdown -->
              {% avatar user 30 %}
            </ul> <!-- nav -->
          </div> <!-- container -->
        </div> <!-- navbar-inner -->
      </div> <!-- navbar -->
    </div> <!-- span -->
  </div> <!-- row -->
  <div class="row-fluid" id="structure">
    <div class="span12">
      <div class="row-fluid">
        <div class="span3 offset2">
          {% block sidebar %}
          {% endblock sidebar %}
        </div> <!-- span4 -->
        <div class="span5 " id="main">
          {% block main %}
          {%endblock main %}
        </div> <!-- span6 -->
      </div> <!-- row1 -->
    </div> <!-- span12 -->
  </div> <!-- row0 -->

</div> <!-- container -->
{% endblock body %}

darkoob/templates/base/search_base.html
{% load staticfiles %}
<html>
  <head>
    <title>AJAX SEARCH</title>
      <style>

        body {
          background-color: #FFF;
          font-size: 1.0em;
          font-family: “Lucida Grande”, Tahoma, Helvetica, sans-serif;
          color: #564b47;
          padding: 20px;
          margin: 0px;
          text-align: center;
            }

        div { 
          padding: 0;
          margin: 0; 
        }

        table { 
          width: 100%; 
          border: 1px solid #DDDDB2;
          border-spacing: 0;
          border-collapse: collapse; 
        }

        tr { 
          padding-bottom: 5px;
          border-bottom: 1px solid #CCC; 
        }

        tr.odd { background: #FFF; }

        tr.even { background: #FFFFD4; }

        td { 
          margin: 0; 
          padding: 5px 5px 5px 3px;
          vertical-align: top; 
        }

        td.right { text-align: right; }

        #centered {
          text-align: left;
          vertical-align: middle;
          margin: 0px auto;
          padding: 20px;
          width: 550px;
          background-color: #FFF;
          border: 1px solid #CCC;
          }
          // az inja kopyeye
        #spinner { 
          display: none;
          position: relative; 
        }

        div.padded { padding-top: 10px; }

        div.margin { margin-top: 20px; }

        div.clear { clear: both; }

        div.note {
          padding: 15px; 
          background: #FFFFD4;
          border: 1px solid #DDDDB2; 
        }

        .hint { 
          font-size: 0.8em;
          color: #888; 
        }

        input{
        	font-size:30px;
        	color:#444;
        	border:1px solid #ccc;
        	padding:5px 10px;
        	box-shadow:0px 1px 0px #fff;
          -moz-box-shadow:0px 1px 0px #fff;
          -webkit-box-shadow:0px 1px 0px #fff;
          -moz-border-radius:6px;
          -webkit-border-radius:6px;
          border-radius:6px;
          -khtml-border-radius:6px;
          margin:5px 10px;
        	width:540px;
        	height:50px;
        }

        input[type="submit"]{
        	font-size:20px;
        	height:40px;
        	font-weight: bolder;
        }

    </style>

    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
	  <script src="{% static "js/endless.js" %}" type="text/javascript" charset="utf-8" ></script>
    <script src="{% static "js/endless_on_scroll.js" %}" type="text/javascript" charset="utf-8" ></script>
    {% block extra_js %}{% endblock %}
  </head>
  <body>
    <div id="centered">
      {% block main %}{% endblock %}
    </div>
  </body>
</html>