darkoob/group/urls.py
from django.conf.urls import patterns, include, url
from darkoob.group import views as group_view
from darkoob.social import views as social_view

urlpatterns = patterns('',
    url(r'^(?P<group_id>\d+)/(?P<group_name>\w+)/$', group_view.group, name='group_page'),
    url(r'^new/$', group_view.create_group, name='create_group'),
    url(r'^look/$', social_view.user_lookup),
    # url(r'^rate/$', book_views.rate, name='rate'),

)

darkoob/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from darkoob import views 
from darkoob import ajax 


dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # search url
    url(r'^search/', include('haystack.urls')),
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Static URL
    url(r'', include('django.contrib.staticfiles.urls')),

    # Dajaxice URLs 
    url(r'^ajaxice', views.index),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),

    # Project-specific URLs
    url(r'^$', views.index, name='index'),
    url(r'', include('darkoob.social.urls', namespace='social', app_name='socials')),
    url(r'', include('darkoob.migration.urls', namespace='migration')),

    url(r'^book/', include('darkoob.book.urls', namespace='book')),
    url(r'^group/', include('darkoob.group.urls', namespace='group')),
    # Search 
    # TODO: Move to search application
    url(r'', include('darkoob.search.urls', namespace='search')),

    # url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^avatar/', include('avatar.urls')),
)

from django.conf import settings
media_root = getattr(settings, 'MEDIA_ROOT', '/media')    

urlpatterns += patterns('', 
url(r'^media/(?P<path>.*)$','django.views.static.serve',
    {'document_root': media_root})
)

darkoob/group/models.py
from django.db import models
from darkoob.social.models import User
from darkoob.book.models import Book
from django.utils import timezone
   

class Group(models.Model):
    name = models.CharField(max_length=255)
    comment = models.TextField(help_text=u'Description of Group')
    admin = models.ForeignKey(User, related_name='admin_set')
    members = models.ManyToManyField(User, related_name='group_set', null=True)
    created_time = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return unicode(self.name)

class Schedule(models.Model):
    group = models.ForeignKey(Group)
    book = models.ForeignKey(Book)
    submitted_time = models.DateTimeField(default=timezone.now())

    def __unicode__(self):
        return unicode("%s - %s" % (self.group.name, self.book.title))

class Deadline(models.Model):
    schedule = models.ForeignKey(Schedule)
    from_page = models.PositiveIntegerField()
    to_page = models.PositiveIntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __unicode__(self):
        return unicode("%s, %s from page %g to %g" % (
            self.schedule.group.name,
            self.schedule.book.title,
            self.from_page,
            self.to_page,
        ))

darkoob/group/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import AuthenticationForm

class GroupForm(forms.Form):
    name = forms.CharField(max_length=255)
    members = forms.CharField(widget=forms.HiddenInput())

darkoob/group/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from darkoob.group.forms import GroupForm
from darkoob.group.models import Group

def group(request, group_id, group_name):
    group = Group.objects.get(id=group_id, name=group_name)
    if group:
        group.admins = group.admin.admin_set.all()
        #group.members = group.members.all()
        return render(request, "group/group_page.html" ,{'group': group})
    else:
        return HttpResponse("Group Is not exist!")

@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            group = Group(name=cd['name'], admin=request.user)
            group.save()
            for member in cd['members'].strip(',').split(','):
                user = User.objects.get(username=member)
                group.members.add(user)
            group.save()
            
    else:
        form = GroupForm()
    return render(request, 'group/create_group.html', {'form': form })

darkoob/group/templates/group/create_group.html
{% extends "base/profile_base.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}



{% block title %}Group{% endblock title %}

{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span10 sidebox">
        <legend>Groups</legend>
        <p>
          list<br />
          of<br />
          groups
        </p>
      </div> <!-- span10 -->
    </div> <!-- row -->
    <div class="row-fluid">
      <div class="span10 sidebox">
        <legend>Books</legend>
        <p>
          some<br />
          books
        </p>
      </div> <!-- span10 -->
    </div> <!-- row -->
  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock sidebar %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="simple-box">
          <p>
            
          </p>
          <form id="add_group_form" action='{% url "group:create_group" %}' method='post'>
           {% csrf_token %}
           {{ form.name }}
           {{ form.members }}
           <button type="button" id="add_group_button" onmousedown="load_members()" class="btn btn-primary">Add Group</button>
         </form>
         <style>
          .typeahead_wrapper { display: block; height: 30px; }
          .typeahead_photo { float: left; max-width: 30px; max-height: 30px; margin-right: 5px; }
          .typeahead_labels { float: left; height: 30px; }
          .typeahead_primary { font-weight: bold; }
          .typeahead_secondary { font-size: .8em; margin-top: -5px; }
         </style>
         <script src="{% static "/static/js/underscore.min.js" %}"></script>
         <script type="text/javascript">
         function duplicat_group (data) {
          if(data.is_exist) {
            $.pnotify({
              title: 'Duplicated Group',
              text: 'This group is already exist',
              type: 'info',
              opacity: .8
            });
            return false;
          }
          return true;
         }
         function load_members(){
          var member_list = ''

          $('.media').each(function(){
            member_list+=$(this).attr('id') + ',';
          })
          $('#id_members').val(member_list);
          Dajaxice.darkoob.group.is_group_exist(duplicat_group, {'group_name': $('#id_name').val()});
         }

         $(document).ready(function() {

          $(function(){

            var bondObjs = {};
            var bondNames = [];

      //get the data to populate the typeahead (plus an id value)
      var throttledRequest = _.debounce(function(query, process){
        //get the data to populate the typeahead (plus an id value)
        $.ajax({
          url: '/group/look'
          ,type: "GET"
          ,data: { query: $('#user-look').val()}
          ,cache: false
          ,success: function(data){
            //reset these containers every time the user searches
            //because we're potentially getting entirely different results from the api
            bondObjs = {};
            bondNames = [];

            //Using underscore.js for a functional approach at looping over the returned data.
            _.each( data, function(item, ix, list){

              //for each iteration of this loop the "item" argument contains
              //1 bond object from the array in our json, such as:
              // { "id":7, "name":"Pierce Brosnan" }

              //add the label to the display array
              bondNames.push( item.username );

              //also store a hashmap so that when bootstrap gives us the selected
              //name we can map that back to an id value
              bondObjs[ item.username ] = item;
            });

            //send the array of results to bootstrap for display
            process( bondNames );
          }
        });
});


$(".typeahead").typeahead({
  source: function ( query, process ) {

          //here we pass the query (search) and process callback arguments to the throttled function
          throttledRequest( query, process );

        }
        ,highlighter: function( item ){
          var bond = bondObjs[ item ];
          
          return '<div class="bond">'
          + "<div class='typeahead_wrapper'>"
          +'<img class=\'typeahead_photo\' src="' + bond.photo + '" />'
          + "<div class='typeahead_labels'>"
          +'<div class=\'typeahead_primary\'>' + bond.username + '</div>'
          + "<div class='typeahead_secondary'>" + bond.full_name + "</div>"
          +'</div>'
          +'</div>';
        }
        , updater: function ( selectedName ) {

          //note that the "selectedName" has nothing to do with the markup provided
          //by the highlighter function. It corresponds to the array of names
          //that we sent from the source function.

          //save the id value into the hidden field
          $( "#user-look" ).val( bondObjs[ selectedName ].id );

          //return the string you want to go into the textbox (the name)
          return selectedName;
        }
      });
  });
});

function close_added_user(added_user)
{
  $(added_user).remove();

}
</script>
<div id="added-users"></div>
<br />

<input
  type="text"
  id="user-look"
  class="span6 typeahead"
  placeholder="Username"
  autocomplete="off"
  data-provide="typeahead"
/>

<script type="text/javascript">
function is_in_added_users(username)
{
  var result = false
  if($('#added-users').children().length > 0) {
    $('#added-users').children().each(function(index, user) {
      if (user.id == username) {
        result = true;
      }
    });
  }
  return result;
}

function is_user_callback(data)
{
  if (data.is_exist ) {
    if (!is_in_added_users($('#user-look').val())) {
      $('#added-users').append(
        '<div class="media" id="'+ $('#user-look').val() +'" >' +
        '<a class="pull-left" href="#">' +
        '<img class="media-object" src="'+ data.url +'">'+
        '</a><div class="media-body">' +
        '<button class="close" id="close_button" onmousedown="close_added_user(\'#'+$('#user-look').val()+'\')">&times;</button>'+
        '<b class="media-heading">'+ $('#user-look').val() +'</b><br/>' +
        data.full_name +
        '</div>' +
        '</div>'
        )
    } else {
      $.pnotify({
        title: 'Duplicated Username',
        text: 'This user is already added',
        type: 'info',
        opacity: .8
      });
    }
  } else {
    $.pnotify({
      title: 'Not Exist',
      text: 'Wrong username , be sure what you looking for!',
      type: 'error',
      opacity: .8
    });
  }
}
$('#user-look').keypress(function(e) {
  if(e.which == 13) {
    Dajaxice.darkoob.social.is_user(is_user_callback, {'username': $('#user-look').val()});
  }
});
</script>
</div>
</div> <!-- span12 -->
</div> <!-- row -->
</div> <!-- span -->
</div> <!-- row -->
{% endblock main %}

darkoob/group/templates/group/group_page.html
{% extends "base/profile_base.html" %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/less" href="{% static "/static/css/profile_base_style.less" %}">
<link rel="stylesheet" type="text/less" href="{% static "/static/css/home_style.less" %}">
{% endblock css %}



{% block title %}Group{% endblock title %}

{% block sidebar %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span10 sidebox">
        <legend>Books</legend>
      </div> <!-- span10 -->
    </div> <!-- row -->
    <div class="row-fluid">
      <div class="span10 sidebox">
        <legend>Schedules</legend>
        
      </div> <!-- span10 -->
    </div> <!-- row -->
     <div class="row-fluid">
      <div class="span10 sidebox">
        <legend>Members</legend>
          <ul>
            <li><a>{{ group.admin }}</a></li>
            {% for member in group.members.all %}
              <li><a>{{ member }}</a></li>
            {% endfor %}
          </ul>
      </div> <!-- span10 -->
    </div> <!-- row -->
  </div> <!-- span12 -->
</div> <!-- row -->
{% endblock sidebar %}

{% block main %}
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <div class="simple-box">
          <p>{{ group.name }}</p>
        </div>
      </div> <!-- span12 -->
    </div> <!-- row -->
  </div> <!-- span -->
</div> <!-- row -->
{% endblock main %}